/// <reference types="react-native-css/types" />
 
<<<<<<< HEAD
// NOTE: This file should not be edited and should be committed with your source code. It is generated by 
// 
// react-native-css. If you need to move or disable this file, please see the documentation.
=======
// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.
>>>>>>> 9456fdd45ed5fb25924e0400d29c5b37dab20e10
